apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    role: alert-rules
    release: prometheus # Этот лейбл должен совпадать с именем релиза вашего Helm-чарта
text:
spec:
  groups:
    - name: infrastructure_alerts
      rules:
        # 1. Критический алерт: Если под или инстанс упал и лежит больше 1 минуты
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Инстанс {{ $labels.instance }} недоступен!"
            description: "Компонент {{ $labels.instance }} в джобе {{ $labels.job }} лежит дольше 1 минуты."

        # 2. Ворнинг алерт: Высокая нагрузка на процессор (CPU)
        - alert: HighCPUUsage
          expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Высокая нагрузка на CPU на {{ $labels.instance }}"
            description: "Использование процессора поднялось выше 80% за последние 2 минуты."

    - name: sre_slo_alerts
      rules:
        # 3. HTTP 5xx Ошибки (Нарушение SLO по ошибкам)
        - alert: HighHttpErrorRate
          expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Высокий уровень ошибок HTTP 5xx"
            description: "Процент серверных ошибок превышает 5% за последние 5 минут на инстансе {{ $labels.instance }}."

        # 4. Latency / Задержка (Нарушение SLO по скорости ответа)
        - alert: SlowResponseTime
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Медленный ответ сервера (High Latency)"
            description: "95-й перцентиль времени ответа сервера превышает 500мс (0.5 сек) за последние 2 минуты."