apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-capstone-alerts
  namespace: sre-capstone
  labels:
    role: alert-rules
spec:
  groups:
    - name: sre_infrastructure_alerts
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Компонент кластера недоступен!"
            description: "Инстанс {{ $labels.instance }} лежит дольше 1 минуты."

        - alert: HighCPUUsage
          expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Высокая нагрузка на CPU!"
            description: "Использование CPU поднялось выше 80% за последние 2 минуты."