apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    # Этот лейбл говорит Prometheus Operator подхватить этот Monitor
    release: prometheus 
spec:
  # Указываем, какие сервисы искать (выставим лейбл, который Участник 2 даст при деплое)
  selector:
    matchLabels:
      app: prediction-market-app 
  namespaceSelector:
    any: true
  endpoints:
  - port: web # Имя порта в сервисе приложения, который отдает метрики
    path: /metrics # Путь, по которому Prometheus будет забирать данные
    interval: 15s # Как часто собирать метрики